### ISSUE TITLE
AttributeError: 'Rule' object has no attribute 'is_readonly'

### ISSUE THREAD

**Issue by mbehrle** [openlabs/nereid#242]
Commit f690d8b476b010522567ef578d00c84e1dd76e04 introduced the following regression on all my test systems (also a new built one from scratch):

127.0.0.1 - - [19/Dec/2014 12:43:52] "GET /de-de/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mathiasb/.virtualenvs/nereid-webshop3.2/lib/python2.7/site-packages/nereid/application.py", line 423, in dispatch_request
    readonly=rule.is_readonly) as txn:
AttributeError: 'Rule' object has no attribute 'is_readonly'

It seems, that req.url_rule doesn't return the correct class defined in url_rule_class = Rule.

**Comment by sharoonthomas** [comment]
@mbehrle The problem requires a fix in werkzeug and I have sent a pr [1].

In the meantime @tarunbhardwaj will send a PR for 3.2 and 3.4 which fixes the issue within nereid for sometime.

[1] https://github.com/mitsuhiko/werkzeug/pull/645

**Comment by sharoonthomas** [comment]
This shoudl now be fixed.

Thank you @mbehrle and @tarunbhardwaj

**Comment by mbehrle** [comment]
* Sharoon Thomas: " Re: [nereid] AttributeError: 'Rule' object has no attribute
  'is_readonly' (#242)" (Wed, 31 Dec 2014 22:13:32 -0800):

> This shoudl now be fixed.
> 
> Thank you @mbehrle and @tarunbhardwaj 

Thanks!

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6
